export const CARDS_12 = [
	{ id: 1, cardContent: "image1" },
	{ id: 2, cardContent: "image2" },
	{ id: 3, cardContent: "image3" },
	{ id: 4, cardContent: "image4" },
	{ id: 5, cardContent: "image5" },
	{ id: 6, cardContent: "image6" },
	{ id: 7, cardContent: "image1" },
	{ id: 8, cardContent: "image2" },
	{ id: 9, cardContent: "image3" },
	{ id: 10, cardContent: "image4" },
	{ id: 11, cardContent: "image5" },
	{ id: 12, cardContent: "image6" },
];
export const CARDS_18 = [
	{ id: 1, cardContent: "image1" },
	{ id: 2, cardContent: "image2" },
	{ id: 3, cardContent: "image3" },
	{ id: 4, cardContent: "image4" },
	{ id: 5, cardContent: "image5" },
	{ id: 6, cardContent: "image6" },
	{ id: 7, cardContent: "image7" },
	{ id: 8, cardContent: "image8" },
	{ id: 9, cardContent: "image9" },
	{ id: 10, cardContent: "image1" },
	{ id: 11, cardContent: "image2" },
	{ id: 12, cardContent: "image3" },
	{ id: 13, cardContent: "image4" },
	{ id: 14, cardContent: "image5" },
	{ id: 15, cardContent: "image6" },
	{ id: 16, cardContent: "image7" },
	{ id: 17, cardContent: "image8" },
	{ id: 18, cardContent: "image9" },
];
export const CARDS_24 = [
	{ id: 1, cardContent: "image1" },
	{ id: 2, cardContent: "image2" },
	{ id: 3, cardContent: "image3" },
	{ id: 4, cardContent: "image4" },
	{ id: 5, cardContent: "image5" },
	{ id: 6, cardContent: "image6" },
	{ id: 7, cardContent: "image7" },
	{ id: 8, cardContent: "image8" },
	{ id: 9, cardContent: "image9" },
	{ id: 10, cardContent: "image10" },
	{ id: 11, cardContent: "image11" },
	{ id: 12, cardContent: "image12" },
	{ id: 13, cardContent: "image1" },
	{ id: 14, cardContent: "image2" },
	{ id: 15, cardContent: "image3" },
	{ id: 16, cardContent: "image4" },
	{ id: 17, cardContent: "image5" },
	{ id: 18, cardContent: "image6" },
	{ id: 19, cardContent: "image7" },
	{ id: 20, cardContent: "image8" },
	{ id: 21, cardContent: "image9" },
	{ id: 22, cardContent: "image10" },
	{ id: 23, cardContent: "image11" },
	{ id: 24, cardContent: "image12" },
];
